baseURL = "https://anandsharma-i.github.io/portfolio"
relativeURLs = true
title = "Soumyakant Padhee"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[author]
name = "Lei Yang"
homepage = "http://leiy.me/"

[params]
goatcounter = "leiy"
PGPFingerprint = "2D3EB894C40AE453"
PGPPubkeyLink = "https://keybase.io/yangl1996/pgp_keys.asc?fingerprint=233a3c408f6e5d3fcc13802f2d3eb894c40ae453"
shortbio = "Ph.D. student in Computer Science"
officeAddress = "21 Worthington St., Unit-2,Boston, Massachusetts,02120, USA"
officeMapLink = "https://www.csail.mit.edu/sites/default/files/resources/maps/9G/G918.gif"
profileurl = "https://media-exp1.licdn.com/dms/image/C4E03AQE836lixhfZCg/profile-displayphoto-shrink_800_800/0/1660597061776?e=2147483647&v=beta&t=8fQ4P7rRYLNLr-8q57_770BQlNzXrPI829Lq0uKJJ0o"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

