baseurl = "https://anandsharma-i.github.io/portfolio"
canonifyurls = true
relativeURLs = true
title = "Soumyakant Padhee"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[author]
name = "Soumyakant Padhee"
homepage = "http://leiy.me/"


[params]
#goatcounter = "leiy"
#PGPFingerprint = "2D3EB894C40AE453"
#PGPPubkeyLink = "https://keybase.io/yangl1996/pgp_keys.asc?fingerprint=233a3c408f6e5d3fcc13802f2d3eb894c40ae453"
shortbio = "Ph.D. Candidate, Industrial Engineering (expected July 2023)"
officeAddress = "21 Worthington St., Unit-2,Boston, Massachusetts,02120, USA"
officeMapLink = "https://goo.gl/maps/Nd2AU47iyTT7s1vS8"
#profileurl = "https://media-exp1.licdn.com/dms/image/C4E03AQE836lixhfZCg/profile-displayphoto-shrink_800_800/0/1660597061776?e=2147483647&v=beta&t=8fQ4P7rRYLNLr-8q57_770BQlNzXrPI829Lq0uKJJ0o"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

